In [1]:
import numpy as np
from sklearn import datasets

In [2]:
# 加载鸢尾花数据集
iris = datasets.load_iris()
X = iris.data
y = iris.target.copy()
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
# 转换成二分类问题
y[y!=0] = 1
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=86)

logistic_regression = LogisticRegression()
logistic_regression.fit(X_train,y_train)
y_predict = logistic_regression.predict(X_test)

In [5]:
TN = np.sum((y_predict==0)&(y_test==0))
TN

11

In [6]:
FP = np.sum((y_predict==1)&(y_test==0))
FP

0

In [7]:
FN = np.sum((y_predict==0)&(y_test==1))
FN

0

In [8]:
TP = np.sum((y_predict==1)&(y_test==1))
TP

27

In [9]:
confusion_matrix = np.array([
    [TN,FP],
    [FN,TP]
])
confusion_matrix

array([[11,  0],
       [ 0, 27]])

In [10]:
precision = TP/(FP+TP)
# 表示预测为正例的样本中，真正为正例的比例
precision

1.0

In [11]:
recall = TP/(FN+TP)
# 表示真实正例中被正确预测的比例
recall

1.0

In [12]:
f1_score = 2*precision*recall/(precision+recall)
# 精确率与召回率的调和平均值
f1_score

1.0

### scikit-learn中封装实现

In [14]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_predict)

array([[11,  0],
       [ 0, 27]], dtype=int64)

In [15]:
from sklearn.metrics import precision_score

precision_score(y_test,y_predict)

1.0

In [16]:
from sklearn.metrics import recall_score

recall_score(y_test,y_predict)

1.0

In [17]:
from sklearn.metrics import f1_score

f1_score(y_test,y_predict)

1.0