## 1.加载数据集

In [5]:
import numpy as np
from sklearn import datasets 

In [7]:
iris = datasets.load_iris() #鸢尾花数据集

In [11]:
iris 
#150个分为三个品种，每个品种50个样本 
#4个数值型特征 3个分类标签

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [15]:
iris.keys()
# 查看鸢尾花数据集（iris）的内部结构，获取数据集包含的所有键（key）
# 原理：在scikit_learn中加载的数据集以类似字典的从结构存储通过keys()方法可以查看其组成部分
# 'data':存储样本的特征数据
# 'target':存储样本的分类标签用数字编码，分别对应不同的鸢尾花品种）
# 'feature_names':特征名称
# DESCR:数据集描述信息（包含数据集来源、特征说明等）

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [19]:
X = iris.data
# 从数据集中提取特征数据，赋值给变量X
# iris.data是一个二维数组每一行代表一个样本每一列对应一个特征（按feature_names的顺序排列）

In [25]:
iris.data.shape

(150, 4)

In [27]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [29]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [31]:
iris.target.shape

(150,)

In [33]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 2.拆分数据集

In [36]:
shuffle_index = np.random.permutation(len(y))
shuffle_index

array([100,  51,  80, 123, 117, 129,  45,   2,  40, 106,  10, 145,  78,
        13,  60,  52, 126,  77,  63, 111,  62,   5,  84,  22, 127,  32,
        85,  97,  28,  69,  17,  66,  38, 115,  36,  23,  20,  74,  98,
         1,  73,  59,  82,  86,  26,  55,  94, 148, 144,  11,  61,  79,
        50,  71,  93,   3,  47,  14,  83, 101, 143, 132,  92, 114, 107,
       135,  15,  88, 109,  16,   0, 108,   7, 139,  42,  21, 122,  43,
       119,  67,   4, 141, 113,  99,  19,   6, 112,  54, 118,   8,  34,
       125, 102, 133,  72,  39, 128,  56, 142, 146,  29, 147, 130, 124,
       140,  24,  57,  68,  37,  75,  12,  91, 104, 131,  25,  31,  41,
        76,  96, 105,  46,  65,  87, 134,  95, 138,  33, 110,  89, 121,
        90, 103,   9,  44,  35,  81, 120,  53,  30, 149,  48,  18, 116,
        64,  27,  49, 137,  70, 136,  58])

In [38]:
train_ratio = 0.8

In [40]:
train_size = int(len(y)*train_ratio)
train_size

120

In [44]:
train_index = shuffle_index[:train_size]
test_index = shuffle_index[train_size:]

array([100,  51,  80, 123, 117, 129,  45,   2,  40, 106,  10, 145,  78,
        13,  60,  52, 126,  77,  63, 111,  62,   5,  84,  22, 127,  32,
        85,  97,  28,  69,  17,  66,  38, 115,  36,  23,  20,  74,  98,
         1,  73,  59,  82,  86,  26,  55,  94, 148, 144,  11,  61,  79,
        50,  71,  93,   3,  47,  14,  83, 101, 143, 132,  92, 114, 107,
       135,  15,  88, 109,  16,   0, 108,   7, 139,  42,  21, 122,  43,
       119,  67,   4, 141, 113,  99,  19,   6, 112,  54, 118,   8,  34,
       125, 102, 133,  72,  39, 128,  56, 142, 146,  29, 147, 130, 124,
       140,  24,  57,  68,  37,  75,  12,  91, 104, 131,  25,  31,  41,
        76,  96, 105])

In [46]:
X_train = X[train_index]
y_train = y[train_index]

X_test = X[test_index]
y_test = y[test_index]

In [48]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [50]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


### 封装数据集划分

In [57]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size = 0.8,random_state = 666)

In [59]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [61]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


## 3.预测

In [95]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors=5)
# 初始化KNN分类器设置邻近样本数为5

In [97]:
knn_classifier.fit(X_train,y_train)
# 使用训练数据集特征X_train和标签y_train对模型进行训练（拟合），让模型学习数据特征与标签的映射关系

KNeighborsClassifier()

In [99]:
knn_classifier.score(X_test,y_test)

1.0

In [101]:
y_predict=knn_classifier.predict(X_test)
y_predict

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2])

## 4.评价

In [71]:
y_test

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2])

In [75]:
np.sum(y_predict == y_test)

30

In [79]:
accuracy = np.sum(y_predict == y_test)/ len(y_test)
accuracy

1.0

In [85]:
from sklearn.metrics import accuracy_score

In [89]:
accuracy_score(y_test,y_predict)

1.0