## Min_Max Scaling

In [2]:
import numpy as np
from sklearn import datasets

In [3]:
# 加载鸢尾花数据集
iris = datasets.load_iris()

In [4]:
X = iris.data
y = iris.target

In [5]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [6]:
np.max(X[:,0])

7.9

In [7]:
np.min(X[:,0])

4.3

In [8]:
X[:,0] = (X[:,0]-np.min(X[:,0])) / (np.max(X[:,0])-np.min(X[:,0]))

In [9]:
X[:5,0]

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444])

In [10]:
X[:,1] = (X[:,1]-np.min(X[:,1])) / (np.max(X[:,1])-np.min(X[:,1]))
X[:,2] = (X[:,2]-np.min(X[:,2])) / (np.max(X[:,2])-np.min(X[:,2]))
X[:,3] = (X[:,3]-np.min(X[:,3])) / (np.max(X[:,3])-np.min(X[:,3]))

In [11]:
X[:5]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667]])

## Zero-Score Normalization

In [13]:
iris = datasets.load_iris()
X=iris.data
y=iris.target

In [14]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [15]:
np.mean(X[:,0])

5.843333333333334

In [16]:
np.std(X[:,0])

0.8253012917851409

In [17]:
X[:,0] = (X[:,0] - np.mean(X[:,0])) / np.std(X[:,0])

In [18]:
X[:5,0]

array([-0.90068117, -1.14301691, -1.38535265, -1.50652052, -1.02184904])

In [19]:
np.mean(X[:,0])

-4.736951571734001e-16

In [20]:
np.std(X[:,0])

1.0

In [21]:
X[:,1] = (X[:,1] - np.mean(X[:,1])) / np.std(X[:,1])
X[:,2] = (X[:,2] - np.mean(X[:,2])) / np.std(X[:,2])
X[:,3] = (X[:,3] - np.mean(X[:,3])) / np.std(X[:,3])

In [22]:
X[:5]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

## scikit-learn 中的StandardScaler

In [24]:
iris = datasets.load_iris()
X=iris.data
y=iris.target

In [25]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [26]:
from sklearn.preprocessing import StandardScaler
# StandardScaler类用于实现数据的标准化处理（即零均值归一化）

In [27]:
standard_scaler = StandardScaler()
# 实例化StandardScaler对象，创建标准化工具

In [28]:
standard_scaler.fit(X)
# 通过输入数据X，计算数据各个特征值的均值（mean_）和标准差（scale_）

StandardScaler()

In [29]:
standard_scaler.mean_

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [30]:
standard_scaler.scale_

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [31]:
X = standard_scaler.transform(X)

In [32]:
X[:5,0]

array([-0.90068117, -1.14301691, -1.38535265, -1.50652052, -1.02184904])