### 数据准备

In [3]:
import numpy as np
state = np.array(['认真复习', '简单复习', '没有复习'])
grade = np.array(['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-'])
n_state = len(state)
m_grade = len(grade)
pi = np.ones(n_state)/n_state
t = np.array([
    [0.4, 0.3, 0.3],
    [0.3, 0.4, 0.3],
    [0.3, 0.3, 0.4]
])
e = np.zeros([3,9])
e[0, :9]=1/9
e[1, 3:9]=1/6
e[2, 5:9]=1/4

In [5]:
print("初始概率矩阵：\n",pi)
print("转移矩阵：\n",t)
print("发射矩阵：\n",e)

初始概率矩阵：
 [0.33333333 0.33333333 0.33333333]
转移矩阵：
 [[0.4 0.3 0.3]
 [0.3 0.4 0.3]
 [0.3 0.3 0.4]]
发射矩阵：
 [[0.11111111 0.11111111 0.11111111 0.11111111 0.11111111 0.11111111
  0.11111111 0.11111111 0.11111111]
 [0.         0.         0.         0.16666667 0.16666667 0.16666667
  0.16666667 0.16666667 0.16666667]
 [0.         0.         0.         0.         0.         0.25
  0.25       0.25       0.25      ]]


### HMM Learn

In [8]:
pip install hmmlearn

Note: you may need to restart the kernel to use updated packages.


In [24]:
from hmmlearn.hmm import CategoricalHMM
hmm = CategoricalHMM(n_state)

In [26]:
hmm.startprob_ = pi
hmm.transmat_ = t
hmm.emissionprob_ = e
hmm.n_feature = 9

In [48]:
datas = np.array([0,4,2,6,1])
datas = np.expand_dims(datas, axis = 1)
# 将一维数组datas扩展为二维数组(形状从(5，)变为(5，1))
states = hmm.predict(datas)

In [50]:
states

array([0, 0, 0, 2, 0], dtype=int64)

In [52]:
prob = hmm.score(datas)
# 计算观测序列datas的对数概率
# score方法返回对数概率值(为数值稳定性，避免直接计算极小值概率)
prob

-14.003674820375014

In [46]:
print(np.exp(prob))
# 对对数概率prob取指数，还原真实概率值

8.284786081615825e-07


In [54]:
datas , states = hmm.sample(10000)

In [56]:
t_2 = np.zeros([3,3])
for i in range(3):
    current = np.where(states == i)[0]
    next_index = current+1
    next_index = next_index[:-1]

    tmp = states[next_index]
    for j in range(3):
        t_2[i][j] = np.where(tmp==j)[0].shape[0]/np.shape(tmp)[0]
print(t_2)

[[0.41429    0.2987091  0.2870009 ]
 [0.29670006 0.41337655 0.28992339]
 [0.28850856 0.30440098 0.40709046]]


In [58]:
e_2 = np.zeros([3,9])
for i in range(3):
    current = np.where(states == i)[0]
    next_index = current+1
    next_index = next_index[:-1]
    tmp = datas[current]
    for j in range(9):
        e_2[i][j] = np.where(tmp==j)[0].shape[0]/np.shape(tmp)[0]
print(e_2)

[[0.10534214 0.11584634 0.10384154 0.11164466 0.11884754 0.11194478
  0.11284514 0.11584634 0.10384154]
 [0.         0.         0.         0.1808542  0.16141384 0.17260677
  0.17113402 0.15552283 0.15846834]
 [0.         0.         0.         0.         0.         0.2578674
  0.24992362 0.23923006 0.25297892]]
